on: [push]

name: AzureARMDeploy

jobs:

    deploy:
      runs-on: windows-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          allow-no-subscriptions: true 
          
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name StorageAccountDeployment \
            --resource-group rg-rani8vish-secure \
            --template-file armtemplates/storageaccount.json \
            --parameters storageAccountType=Standard_GRS
